################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/sw/airborne/arch/linux \
src/sw/airborne/arch/linux/mcu_periph \
src/sw/airborne/arch/linux/subsystems \
src/sw/airborne/arch/sim \
src/sw/airborne/arch/sim/mcu_periph \
src/sw/airborne/arch/sim/modules/core \
src/sw/airborne/arch/sim/modules/enose \
src/sw/airborne/arch/sim/modules/ins \
src/sw/airborne/arch/sim/peripherals \
src/sw/airborne/arch/sim/subsystems/actuators \
src/sw/airborne/arch/sim/subsystems/datalink \
src/sw/airborne/arch/sim/subsystems/radio_control \
src/sw/airborne/arch/sim/subsystems \
src/sw/airborne/boards/ardrone \
src/sw/airborne/boards \
src/sw/airborne/boards/bebop \
src/sw/airborne/firmwares/demo \
src/sw/airborne/firmwares/logger \
src/sw/airborne/firmwares/motor_bench \
src/sw/airborne/firmwares/non_ap/geiger_counter \
src/sw/airborne/firmwares/non_ap/led_flasher \
src/sw/airborne/firmwares/rotorcraft \
src/sw/airborne/firmwares/rotorcraft/guidance \
src/sw/airborne/firmwares/rotorcraft/stabilization \
src/sw/airborne/firmwares/setup \
src/sw/airborne/firmwares/tutorial \
src/sw/airborne \
src/sw/airborne/math \
src/sw/airborne/mcu_periph \
src/sw/airborne/modules/adcs \
src/sw/airborne/modules/ahrs \
src/sw/airborne/modules/air_data \
src/sw/airborne/modules/airborne_ant_track \
src/sw/airborne/modules/benchmark \
src/sw/airborne/modules/calibration \
src/sw/airborne/modules/cam_control \
src/sw/airborne/modules/cartography \
src/sw/airborne/modules/com \
src/sw/airborne/modules/computer_vision \
src/sw/airborne/modules/computer_vision/blob \
src/sw/airborne/modules/computer_vision/lib/encoding \
src/sw/airborne/modules/computer_vision/lib/exif \
src/sw/airborne/modules/computer_vision/lib/v4l \
src/sw/airborne/modules/computer_vision/lib/vision \
src/sw/airborne/modules/computer_vision/opticflow \
src/sw/airborne/modules/computer_vision/qrcode \
src/sw/airborne/modules/config \
src/sw/airborne/modules/core \
src/sw/airborne/modules/ctrl \
src/sw/airborne/modules/datalink \
src/sw/airborne/modules/datalink/missionlib \
src/sw/airborne/modules/demo_module \
src/sw/airborne/modules/digital_cam \
src/sw/airborne/modules/digital_cam/catia \
src/sw/airborne/modules/display \
src/sw/airborne/modules/energy \
src/sw/airborne/modules/enose \
src/sw/airborne/modules/gas_engine \
src/sw/airborne/modules/geo_mag \
src/sw/airborne/modules/gps \
src/sw/airborne/modules/gsm \
src/sw/airborne/modules/guidance_opticflow \
src/sw/airborne/modules/gumstix_interface \
src/sw/airborne/modules/helicopter \
src/sw/airborne/modules/hott \
src/sw/airborne/modules/ins \
src/sw/airborne/modules/light \
src/sw/airborne/modules/loggers \
src/sw/airborne/modules/meteo \
src/sw/airborne/modules/mission \
src/sw/airborne/modules/multi \
src/sw/airborne/modules/nav \
src/sw/airborne/modules/obstacle_avoidance \
src/sw/airborne/modules/optical_flow \
src/sw/airborne/modules/sensors \
src/sw/airborne/modules/servo_switch \
src/sw/airborne/modules/sonar \
src/sw/airborne/modules/stereocam/droplet \
src/sw/airborne/modules/stereocam/nav_line_avoid \
src/sw/airborne/modules/stereocam/state2camera \
src/sw/airborne/modules/stereocam \
src/sw/airborne/modules/stereocam/stereocam2state \
src/sw/airborne/modules/stereocam/stereocam_follow_me \
src/sw/airborne/modules/time \
src/sw/airborne/modules/vehicle_interface \
src/sw/airborne/peripherals \
src/sw/airborne/subsystems/actuators \
src/sw/airborne/subsystems \
src/sw/airborne/subsystems/ahrs \
src/sw/airborne/subsystems/chibios-libopencm3 \
src/sw/airborne/subsystems/datalink \
src/sw/airborne/subsystems/gps \
src/sw/airborne/subsystems/imu \
src/sw/airborne/subsystems/ins \
src/sw/airborne/subsystems/intermcu \
src/sw/airborne/subsystems/navigation \
src/sw/airborne/subsystems/radio_control \
src/var/aircrafts/ardrone2/ap/arch/linux \
src/var/aircrafts/ardrone2/ap/arch/linux/mcu_periph \
src/var/aircrafts/ardrone2/ap/arch/linux/subsystems \
src/var/aircrafts/ardrone2/ap/boards/ardrone \
src/var/aircrafts/ardrone2/ap/firmwares/rotorcraft \
src/var/aircrafts/ardrone2/ap/firmwares/rotorcraft/guidance \
src/var/aircrafts/ardrone2/ap/firmwares/rotorcraft/stabilization \
src/var/aircrafts/ardrone2/ap/math \
src/var/aircrafts/ardrone2/ap \
src/var/aircrafts/ardrone2/ap/mcu_periph \
src/var/aircrafts/ardrone2/ap/modules/air_data \
src/var/aircrafts/ardrone2/ap/modules/calibration \
src/var/aircrafts/ardrone2/ap/modules/geo_mag \
src/var/aircrafts/ardrone2/ap/modules/gps \
src/var/aircrafts/ardrone2/ap/modules/sensors \
src/var/aircrafts/ardrone2/ap/subsystems/actuators \
src/var/aircrafts/ardrone2/ap/subsystems \
src/var/aircrafts/ardrone2/ap/subsystems/ahrs \
src/var/aircrafts/ardrone2/ap/subsystems/datalink \
src/var/aircrafts/ardrone2/ap/subsystems/gps \
src/var/aircrafts/ardrone2/ap/subsystems/imu \
src/var/aircrafts/ardrone2/ap/subsystems/ins \
src/var/aircrafts/ardrone2/ap/subsystems/navigation \
src/var/aircrafts/ardrone2/ap/subsystems/radio_control \

